import Mock from 'mockjs'
// mock数据模拟
// 图表数据
let List =[]
export default {
    getStatissticalData: () => {
        for(let  i=0;i<7;i++){
            List.push(
                Mock.mock({
                    // Mock.Random.float产生随机数100到8000之间，保留小数 最小0位 最大0位
                    苹果:Mock.Random.float(100,8000,0,0),
                    vivo:Mock.Random.float(100,8000,0,0),
                    oppo:Mock.Random.float(100,8000,0,0),
                    魅族:Mock.Random.float(100,8000,0,0),
                    三星:Mock.Random.float(100,8000,0,0),
                    小米:Mock.Random.float(100,8000,0,0),
                })
            )
        }

        return {
            code:2000,
            data:{
                videoData:[
                    {
                        name:'小米',
                        value:2999
                    },
                    {
                        name:'苹果',
                        value:5999
                    },
                    {
                        name:'三星',
                        value:4999
                    },                    
                    {
                        name:'vivo',
                        value:1500
                    },                    
                    {
                        name:'oppo',
                        value:1900
                    },
                    {
                        name:'魅族',
                        value:3999
                    }
                ],
                // 柱状图
                userData:[
                    {
                        data:'周一',
                        new:5,
                        active:200
                    },
                    {
                        data:'周二',
                        new:10,
                        active:500
                    },
                    {
                        data:'周三',
                        new:12,
                        active:550
                    },
                    {
                        data:'周四',
                        new:50,
                        active:204
                    },
                    {
                        data:'周五',
                        new:100,
                        active:309
                    },
                    {
                        data:'周六',
                        new:145,
                        active:200
                    },
                    {
                        data:'周日',
                        new:33,
                        active:170
                    },
                ],
                // 折线图
                orderData:{
                    date:['20191001','20191002','20191003','20191004','20191005','20191006','20191007'],
                    data:List
                },
                tableData:[
                    {
                        name:'oppo',
                        todayBuy:100,
                        monthBuy:300,
                        totalBuy:800
                    },
                    {
                        name:'vivo',
                        todayBuy:100,
                        monthBuy:300,
                        totalBuy:800                    
                    },
                    {
                        name:'Apple',
                        todayBuy:100,
                        monthBuy:300,
                        totalBuy:800
                    },
                    {
                        name:'小米',
                        todayBuy:100,
                        monthBuy:300,
                        totalBuy:800
                    },
                    {
                        name:'三星',
                        todayBuy:100,
                        monthBuy:300,
                        totalBuy:800
                    },
                    {
                        name:'魅族',
                        todayBuy:100,
                        monthBuy:300,
                        totalBuy:800
                    },
                ]
            }
        }
    }
}